---
- name: Linux Investigation Tools
  hosts: localhost
  become: true

  tasks:
    - name: Install Investigation Tools
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - bind9-dnsutils
        - bpfcc-tools
        - bpftrace
        - blktrace
        - cpuid
        - dmidecode
        - dstat
        - ethtool
        - fatrace
        - fio
        - hdparm
        - hping3
        - hwinfo
        - hwloc
        - ifstat
        - iftop
        - iotop
        - iperf3
        - linux-cpupower
        - lldpad
        - lshw
        - lsof
        - lsscsi
        - ltrace
        - msr-tools
        - mtr
        - nicstat
        - numactl
        - pchar
        - pciutils
        - schedtool
        - smartmontools
        - snmp
        - strace
        - sysbench
        - sysstat
        - tcpdump
        - tiptop
        - traceroute
        - util-linux
        - wireless-tools

