---
- name: Configure Rust Development
  hosts: localhost
  become: true

  tasks:
    - name: Install Rust Development Tools
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - cargo
        - rustc
