---
- name: Configure OpenGL/Vulkan Development Environment
  hosts: localhost
  become: true

  tasks:
    - name: Install Development Packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - libglfw3-dev
        - libglm-dev
        - libvulkan-dev
        - python3-pip
        - spirv-tools
        - vulkan-tools
        - vulkan-validationlayers-dev

    - name: Install Python Modules
      ansible.builtin.pip:
        name: glad

